### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by razb** [lamps/redmine_group_assignee#4]
I am unable to get this to work with 1.21

I've tried the current version as well as previous commits. I get this error:

undefined method `labelled_form_for' for #ActionView::Base:0x12dfd560

  On line #1 of vendor/plugins/redmine_group_assignee/app/views/groupext/_general.html.erb

**Comment by lamps** [comment]
sorry...
i have not 1.2.1
maybe...
1.
this file --- vendor/plugins/redmine_group_assignee/app/views/groupext/_general.html.erb
<% labelled_tabular_form_for :group, @group, :url => { :controller => 'groupext', :action => 'update',:id => @group.id} do |f| %>
<%= render :partial => 'form', :locals => { :f => f } %>
<%= submit_tag l(:button_save) %>
<% end %>

Only modify the first line

2.
this file -- vendor\plugins\redmine_group_assignee\app\views\groupext\new.html.erb
2 line modify 
<% labelled_tabular_form_for :group, @group, :url => { :controller => 'groupext', :action => 'create' } do |f| %>

have a good time.... ^^
ps. 1.2, 1.3, 1.4 All the code is different. TT

**Comment by razb** [comment]
Making progress...

Now the problem is with groups with space in the name

> `@Systems Management Team' is not allowed as an instance variable name
> On line #1 of
> vendor/plugins/redmine_group_assignee/app/views/groupext/_form.html.erb

.

park jj reply@reply.github.com wrote:

sorry...
i have not 1.2.1
maybe...
1.
this file --- vendor/plugins/redmine_group_assignee/app/views/groupext/_general.html.erb
<% labelled_tabular_form_for :group, @group, :url => { :controller => 'groupext', :action => 'update',:id => @group.id} do |f| %>
<%= render :partial => 'form', :locals => { :f => f } %>
<%= submit_tag l(:button_save) %>
<% end %>

Only modify the first line

2.
this file -- vendor\plugins\redmine_group_assignee\app\views\groupext\new.html.erb
2 line modify 
<% labelled_tabular_form_for :group, @group, :url => { :controller => 'groupext', :action => 'create' } do |f| %>

have a good time.... ^^
ps. 1.2, 1.3, 1.4 All the code is different. TT

---

**Comment by lamps** [comment]
hi
1.2 1.3 Version of the function has changed..
Applies only to the current version is 1.4.

sorry, but this will also need to modify. (1.2.x , 1.3.x)
redmine_group_assignee / app / views / groupext / _form.html.erb file (This file must be modified)
- 1 line is delete or replace <%= f.error_messages %> 

source link
https://github.com/lamps/redmine_group_assignee/blob/e1972e0dd794584afba5ed0586e02b509e4ccdaf/app/views/groupext/_form.html.erb

have a nice day.. ^^

**Comment by razb** [comment]
Thanks you. It works very well now.
